name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # SETUP
      - uses: actions/checkout@v2

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: .spago

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm ci

      # BUILD
      - name: Build source
        run: npm run build

      # TEST
      - name: Run tests
        run: npm run test

      # COPY TO DIST
      - name: Create dist
        run: mkdir dist

      - name: Copy package.json
        run: cp package.deploy.json dist/package.json

      - name: Copy toml
        run: cp netlify.toml dist/netlify.toml

      - name: Copy out_publish to dist
        run: cp -r --parents out_publish dist

      - name: Copy out_functions to dist
        run: cp -r --parents out_functions dist

      # PUBLISH
      - name: Publish to demo branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: demo
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
